const settings = {
  L1: 0,
  L1settings: { name: "name", id: "id", min: 0, max: 100 },
  L2: 0,
  L2settings: { name: "name", id: "id", min: 0, max: 100 },
  L3: 0,
  L3settings: { name: "name", id: "id", min: 0, max: 100 },
  A1: 0,
  A1settings: { name: "name", id: "id", min: 0, max: 100 },
  A2: 0,
  A2settings: { name: "name", id: "id", min: 0, max: 100 },
  A3: 0,
  A3settings: { name: "name", id: "id", min: 0, max: 100 },
  B1: 0,
  B1settings: { name: "name", id: "id", min: 0, max: 100 },
  B2: 0,
  B2settings: { name: "name", id: "id", min: 0, max: 100 },
  B3: 0,
  B3settings: { name: "name", id: "id", min: 0, max: 100 },
  C1: 0,
  C1settings: { name: "name", id: "id", min: 0, max: 100 },
  C2: 0,
  C2settings: { name: "name", id: "id", min: 0, max: 100 },
  C3: 0,
  C3settings: { name: "name", id: "id", min: 0, max: 100 },
  D1: 0,
  D1settings: { name: "name", id: "id", min: 0, max: 100 },
  D2: 0,
  D2settings: { name: "name", id: "id", min: 0, max: 100 },
  D3: 0,
  D3settings: { name: "name", id: "id", min: 0, max: 100 },
};
